apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-html
data:
  index.html: |
    <html>
    <body>
    <h1>Version 2 - Green</h1>
    <div style="width:100px;height:100px;background:green;"></div>
    </body>
    </html>
